version: '3'
services:
  cms:
    image: guzhongren/cms
    ports:
      - "8090:80"
    links:
      - backend
    depends_on:
      - backend
  backend:
    image: guzhongren/cms-backend
    ports:
      - "1234:1234"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '000000'
      POSTGRES_USER: 'postgres'
    ports:
      - 2345:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
    depends_on:
    - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'guzhongren@live.cn'
      PGADMIN_DEFAULT_PASSWORD: '000000'
    ports:
      - 9099:80