version: '3'
services:
  cms:
    image: guzhongren/cms:latest
    ports:
      - "8091:80"
    links:
      - backend
    depends_on:
      - backend
    networks:
     - backend-network
     - frontend-network
  backend:
    image: guzhongren/cms-backend
    ports:
      - "12345:1234"
    links:
      - db
    depends_on:
      - db
    networks:
     - backend-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '000000'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54321:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
    depends_on:
    - pgadmin
    networks:
     - backend-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'guzhongren@live.cn'
      PGADMIN_DEFAULT_PASSWORD: '000000'
    ports:
      - 9099:80
    networks:
     - backend-network
networks:
  frontend-network:
  backend-network: