version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-watch-create-metrics-guzhongren"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a1b4wsic34ky"
s3_prefix = "cloud-watch-create-metrics-guzhongren"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

