AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Code:
        ZipFile: "var aws = require('aws-sdk')\nvar response = require('cfn-response')\n\
          exports.handler = function(event, context) {\n    console.log(\"REQUEST\
          \ RECEIVED:\\n\" + JSON.stringify(event))\n    // For Delete requests, immediately\
          \ send a SUCCESS response.\n    if (event.RequestType == \"Delete\") {\n\
          \        response.send(event, context, \"SUCCESS\")\n        return\n  \
          \  }\n    var responseStatus = \"FAILED\"\n    var responseData = {}\n \
          \   var functionName = event.ResourceProperties.FunctionName\n    var lambda\
          \ = new aws.Lambda()\n    lambda.invoke({ FunctionName: functionName },\
          \ function(err, invokeResult) {\n        if (err) {\n            responseData\
          \ = {Error: \"Invoke call failed\"}\n            console.log(responseData.Error\
          \ + \":\\n\", err)\n        }\n        else responseStatus = \"SUCCESS\"\
          \n        response.send(event, context, responseStatus, responseData)\n\
          \    })\n}\n"
      Description: Invoke a function to create a log stream.
      MemorySize: 128
      Timeout: 8
      Role: arn:aws:iam::494526681395:role/for-aws-training-2
